root_train_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train"
root_train_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train_mask"
root_valid_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid"
root_valid_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid_mask"
root_test_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/test"
positive_only: False

image_height: 480
image_width: 640

batch_size: 8
loss_function: "ActiveContourLoss"
optimizer: "Nadam"
learning_rate: 0.0001
scheduler: 'CosineAnnealingLR'
T_max: 10
step_size: 30
gamma: 0.1
backbone: "neounet"
classes: ['background', 'neoplastic', 'non-neoplastic']
encoder_weights: 'imagenet'
activation: 'sigmoid'

transform: True
num_epochs: 50
device: 'cuda'
continue_training: False
trained_weights: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/neounet_ac.pt"
save_checkpoint: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/neounet_ac.pt"
csv_name: "neounet_ac"