root_train_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train"
root_train_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train_mask"
root_valid_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid"
root_valid_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid_mask"
root_test_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/test"
positive_only: False

image_height: 960
image_width: 1280

batch_size: 6
loss_function: "CrossEntropyLoss"
optimizer: "Nadam"
learning_rate: 0.0001
scheduler: 'CosineAnnealingWarmRestarts'
T_mult: 2
backbone: "pranet"
classes: ['background', 'neoplastic', 'non-neoplastic']
encoder_weights: 'imagenet'
activation: 
probability_correction_strategy: False

transform: True
num_epochs: 50
device: 'cuda'
continue_training: True
trained_weights: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/pranet_continue.pt"
save_checkpoint: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/pranet_resize.pt"
csv_name: "pranet_resize"