root_train_image_path: "../dataset/pngs/original_images/train"
root_train_label_path: "../dataset/annotations/full_json/train.json"
root_test_image_path: "../dataset/pngs/original_images/test"
root_test_label_path: "../dataset/annotations/full_json/test.json"

image_height: 512
image_width: 512

batch_size: 8
loss_function: "DiceBCELoss"
optimizer: "Adam"
learning_rate: 0.0005
scheduler: 'ReduceLROnPlateau'
step_size: 30
gamma: 0.1
backbone: "resnet34"

annotation_type: json
num_epochs: 10
device: 'cuda'
save_path: "./checkpoints"
continue_training: False
save_checkpoint: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/vinbrain_internship/checkpoints/model-ckpt-best-dicebce.pt"