root_df_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/others_code/nguyen/siimacr/nguyen_preprocessing_data.csv"
root_test_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/nguyen/nguyen_dicom/siim-acr-pneumothorax-segmentation/stage_2_images"
positive_only: False

image_height: 512
image_width: 512

batch_size: 8
loss_function: "MixedLoss"
optimizer: "Nadam"
learning_rate: 0.0001
scheduler: 'CosineAnnealingLR'
T_max: 10
step_size: 30
gamma: 0.1
backbone: "torchvision.resnet50"
weights: {'bce':3, 'dice':1, 'focal':5}
encoder_weights: imagenet

annotation_type: dataframe
transform: True
num_epochs: 50
device: 'cuda'
save_path: "./checkpoints"
continue_training: False
trained_weights: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/vinbrain_internship/checkpoints/unet.pt"
save_checkpoint: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/vinbrain_internship/checkpoints/unet.pt"